//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Salary
    {
        public int ID { get; set; }
        public int Salary_Id { get; set; }
        public int Employee_Id { get; set; }
        public decimal Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Salary Salary1 { get; set; }
    }
}
