//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mandob_Product
    {
        public int ID { get; set; }
        public int Invoice_Mandob_Id { get; set; }
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public int Amount { get; set; }
        public decimal Price_Mowrid { get; set; }
        public decimal Price { get; set; }
        public decimal Taxes { get; set; }
        public Nullable<int> Offer_Product_id { get; set; }
        public Nullable<int> Offer_BonusAmount { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Invoice_Mandob Invoice_Mandob { get; set; }
        public virtual Product Product { get; set; }
    }
}
