//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mandob_Sadad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice_Mandob_Sadad()
        {
            this.Eradats = new HashSet<Eradat>();
            this.Invoice_Mandob_Sadad_Rproduct = new HashSet<Invoice_Mandob_Sadad_Rproduct>();
            this.Masrofats = new HashSet<Masrofat>();
        }
    
        public int ID { get; set; }
        public int Invoice_Id { get; set; }
        public int Sadad_Type_Id { get; set; }
        public System.DateTime Date_Added { get; set; }
        public decimal Money { get; set; }
        public int User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public System.DateTime InDate { get; set; }
        public bool IS_Chekced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eradat> Eradats { get; set; }
        public virtual Invoice_Mandob Invoice_Mandob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob_Sadad_Rproduct> Invoice_Mandob_Sadad_Rproduct { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masrofat> Masrofats { get; set; }
    }
}
