//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mandob_Sadad_Rproduct
    {
        public int ID { get; set; }
        public int Invoice_Mandob_Sadad_id { get; set; }
        public int Return_Invoice_Product_id { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Invoice_Mandob_Sadad Invoice_Mandob_Sadad { get; set; }
        public virtual Product Product { get; set; }
    }
}
