//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mandob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice_Mandob()
        {
            this.Invoice_Mandob_Product = new HashSet<Invoice_Mandob_Product>();
            this.Invoice_Mandob_Sadad = new HashSet<Invoice_Mandob_Sadad>();
            this.Masrofats = new HashSet<Masrofat>();
        }
    
        public int ID { get; set; }
        public int Customer_Type { get; set; }
        public int Invoice_Number { get; set; }
        public int Payment_Type { get; set; }
        public Nullable<int> Mandob_id { get; set; }
        public System.DateTime Date_Invoice { get; set; }
        public string Date_Invoice_Hijri { get; set; }
        public decimal Price { get; set; }
        public decimal Price_Mowrid { get; set; }
        public decimal Taxes { get; set; }
        public decimal Total_Sadad { get; set; }
        public int User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public System.DateTime InDate { get; set; }
        public bool Is_Deleted { get; set; }
        public bool IS_Payed_Omola { get; set; }
        public Nullable<bool> Omola_Type { get; set; }
        public Nullable<decimal> Omola_quota { get; set; }
        public Nullable<decimal> Omola_Money { get; set; }
    
        public virtual Mandob Mandob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob_Product> Invoice_Mandob_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob_Sadad> Invoice_Mandob_Sadad { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masrofat> Masrofats { get; set; }
    }
}
