//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Company_Sadad_Rproduct
    {
        public int ID { get; set; }
        public int Invoice_Company_Sadad_id { get; set; }
        public int Return_Invoice_Product_id { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Invoice_Company_Product Invoice_Company_Product { get; set; }
        public virtual Invoice_Company_Sadad Invoice_Company_Sadad { get; set; }
    }
}
