//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mandob()
        {
            this.Invoice_Mandob = new HashSet<Invoice_Mandob>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sejil { get; set; }
        public string JawalNO { get; set; }
        public string JawalNO2 { get; set; }
        public string Address { get; set; }
        public string Barcode { get; set; }
        public int User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public System.DateTime InDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob> Invoice_Mandob { get; set; }
        public virtual User User { get; set; }
    }
}
