//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Invoice_Company_Product = new HashSet<Invoice_Company_Product>();
            this.Invoice_Mandob_Product = new HashSet<Invoice_Mandob_Product>();
            this.Invoice_Mandob_Sadad_Rproduct = new HashSet<Invoice_Mandob_Sadad_Rproduct>();
            this.Products1 = new HashSet<Product>();
            this.Products11 = new HashSet<Product>();
            this.Products12 = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public int Company_Id { get; set; }
        public decimal Price_Mowrid { get; set; }
        public decimal Price_Unit { get; set; }
        public decimal Taxes { get; set; }
        public int OldAmount { get; set; }
        public Nullable<int> Offer_TargetAmount { get; set; }
        public Nullable<int> Offer_BonusAmount { get; set; }
        public Nullable<int> Offer_Product_id { get; set; }
        public Nullable<int> User_ID { get; set; }
        public System.DateTime InDate { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public Nullable<decimal> Shop_Price { get; set; }
        public Nullable<int> Shop_Offer_TargetAmount { get; set; }
        public Nullable<int> Shop_Offer_BonusAmount { get; set; }
        public Nullable<int> Shop_Offer_Product_id { get; set; }
        public Nullable<decimal> Home_Price { get; set; }
        public Nullable<int> Home_TargetAmount { get; set; }
        public Nullable<int> Home_Offer_BonusAmount { get; set; }
        public Nullable<int> Home_Offer_Product_id { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Company_Product> Invoice_Company_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob_Product> Invoice_Mandob_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mandob_Sadad_Rproduct> Invoice_Mandob_Sadad_Rproduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products11 { get; set; }
        public virtual Product Product2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products12 { get; set; }
        public virtual Product Product3 { get; set; }
    }
}
