//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
