//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_StoreEntities : DbContext
    {
        public DB_StoreEntities()
            : base("name=DB_StoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee_Salary> Employee_Salary { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Eradat_Type> Eradat_Type { get; set; }
        public virtual DbSet<Eradat> Eradats { get; set; }
        public virtual DbSet<Invoice_Company> Invoice_Company { get; set; }
        public virtual DbSet<Invoice_Company_Product> Invoice_Company_Product { get; set; }
        public virtual DbSet<Invoice_Company_Sadad> Invoice_Company_Sadad { get; set; }
        public virtual DbSet<Invoice_Company_Sadad_Rproduct> Invoice_Company_Sadad_Rproduct { get; set; }
        public virtual DbSet<Invoice_Mandob> Invoice_Mandob { get; set; }
        public virtual DbSet<Invoice_Mandob_Product> Invoice_Mandob_Product { get; set; }
        public virtual DbSet<Invoice_Mandob_Sadad> Invoice_Mandob_Sadad { get; set; }
        public virtual DbSet<Invoice_Mandob_Sadad_Rproduct> Invoice_Mandob_Sadad_Rproduct { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Mandob> Mandobs { get; set; }
        public virtual DbSet<Masrofat_Type> Masrofat_Type { get; set; }
        public virtual DbSet<Masrofat> Masrofats { get; set; }
        public virtual DbSet<Omola> Omolas { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<User_Money> User_Money { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserView> UserViews { get; set; }
        public virtual DbSet<View> Views { get; set; }
    }
}
