//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Money
    {
        public int ID { get; set; }
        public int User_Id { get; set; }
        public decimal Money_Invoice_Mandob { get; set; }
        public decimal Money_Sarf { get; set; }
        public decimal Money_Sandok { get; set; }
        public decimal Money_Mada { get; set; }
        public decimal Money_Remain { get; set; }
        public System.DateTime Save_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
