//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ViewID { get; set; }
        public bool Role_Enter { get; set; }
        public bool Role_Save { get; set; }
        public bool Role_Edit { get; set; }
        public bool Role_Delete { get; set; }
    
        public virtual User User { get; set; }
        public virtual View View { get; set; }
    }
}
