//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public int ID { get; set; }
        public int Userid { get; set; }
        public int Viewid { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Action { get; set; }
        public string Operation { get; set; }
    
        public virtual User User { get; set; }
        public virtual View View { get; set; }
    }
}
